name: Deploy proxy & selfcheck
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i --no-audit --no-fund

      - name: Vercel pull (link project)
        run: npx vercel pull --yes --environment=production --token "${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Vercel deploy (Production)
        run: npx vercel deploy --prod --yes --token "${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Ping _selfcheck
        run: |
          set -euo pipefail
          URL="https://circle-proxy.vercel.app/api/circle/_selfcheck"
          echo "GET $URL"
          code=$(curl -sS -o body.json -w "%{http_code}" "$URL")
          cat body.json || true
          if [ "$code" != "200" ]; then
            echo "::error::Selfcheck HTTP $code"
            exit 1
          fi
          jq -e '.ok==true and .upstreamStatus==200' body.json > /dev/null
